# Generated by Django 4.0.4 on 2022-05-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casework', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_price',
        ),
    ]
