# Generated by Django 4.0.4 on 2022-04-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casework', '0002_rename_total_price_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='order', to='casework.drink'),
        ),
    ]
